name: cross-browser-e2e.rb
on: [push]
jobs:
  ie:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6.x'
      - run: bundle install
      - run: bundle exec rspec
        env:
          BROWSER: ie
  # cannot change setting 'Allow Remote Automation'
  # safari:
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v1
  #     - uses: actions/setup-ruby@v1
  #       with:
  #         ruby-version: '2.6.x'
  #     - run: "sudo safaridriver --enable"
  #     - run: "cd Ruby/ && bundle install && bundle exec rspec"
  #       env:
  #         BROWSER: safari
  firefox:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6.x'
      - run: bundle install
      - run: bundle exec rspec
        env:
          BROWSER: firefox
  chrome:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6.x'
      - run: bundle install
      - run: bundle exec rspec
        env:
          BROWSER: chrome
